### ISSUE TITLE
I get this issuse on linux, can you help me please?

### ISSUE THREAD

**Issue by s3nseii** [redianmarku/instagram-dm-bot#2]
![Screenshot 2021-02-19 19:12:46](https://user-images.githubusercontent.com/47414629/108523511-6e642200-72e7-11eb-8e42-aa5fddac9fe5.png)
I need help about that.

**Comment by redianmarku** [comment]
are you using python3

**Comment by redianmarku** [comment]
In Linux and Mac you should use ```python3 bot.py```
